// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgWjes6elG03i-kh60FaUjGmDzli3XhEY',
    appId: '1:764623398624:web:361bb8b498392a455c9285',
    messagingSenderId: '764623398624',
    projectId: 'mealmentor-ai-59502',
    authDomain: 'mealmentor-ai-59502.firebaseapp.com',
    storageBucket: 'mealmentor-ai-59502.firebasestorage.app',
    measurementId: 'G-X1QDER9CHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcmFKWTAFkLZVSBy8KfUVCeHQQdM6FEmA',
    appId: '1:764623398624:android:71d1bc3f8b32dd285c9285',
    messagingSenderId: '764623398624',
    projectId: 'mealmentor-ai-59502',
    storageBucket: 'mealmentor-ai-59502.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ86nK4LFK2kkpBcI7ZloHcfoU0eWc7gQ',
    appId: '1:764623398624:ios:de94038157e639895c9285',
    messagingSenderId: '764623398624',
    projectId: 'mealmentor-ai-59502',
    storageBucket: 'mealmentor-ai-59502.firebasestorage.app',
    iosBundleId: 'com.example.mealmentorai.mealMentor',
  );
}
